language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - sudo apt-get install -y sshpass
script:
  - npm install
  - ./node_modules/.bin/jest --coverage
  - ./node_modules/.bin/codecov
